### ISSUE TITLE
Remove our code from your repository

### ISSUE THREAD

**Issue by deacix** [ConcourseOpen/DEXAG-Proxy#2]
So guys here an official issue. You have 14 days to remove our code from your repository which you have stolen from our etherscan deployment under:

https://etherscan.io/address/0x11111254369792b2Ca5d084aB5eEA397cA8fa48B#code

**Comment by mattnumber** [comment]
Hello - I'm counsel for Concourse and have looked into this. I learned from our CTO that - as I suspected - (1) we didn't steal any code from 1inch and (2) the DEX.AG proxy contract doesn't include or rely on any unauthorized intellectual property. Frankly, it felt a bit insulting for me even to ask our CTO for confirmation of those facts, because we would never knowingly infringe IP rights of any third party; that's just not how we operate.

**Comment by deacix** [comment]
Lol! And why Github deleted the smart contracts from your repo where our code was included?? Just stop lying.. You operate like thiefs!

**Comment by mattnumber** [comment]
Just for the record, your accusations remain false, unfounded, and probably defamatory. GitHub didn't delete the smart contracts, we didn't steal 1inch's code, I'm not lying, and we don't operate like thieves. 

Related: https://twitter.com/DEXAG_TokenWire/status/1197611116425166848?s=20

**Comment by deacix** [comment]
Hey man :) here is one example:
One of the first DEX.ag Proxy Contracts:
https://etherscan.io/address/0xd3bed3a8e3e6b24b740ead108ba776e0ad298588#code

`function infiniteApproveIfNeeded(IERC20 token, address to) internal {
        if (
            address(token) != ETH_ADDRESS &&
            token.allowance(address(this), to) == 0
        ) {
            token.safeApprove(to, uint256(-1));
        }
    }`

Identical function to 100% to one of our earliest versions of 1inch contract.. 
Don't lie, be happy :)

**Comment by mattnumber** [comment]
The contracts are nearly completely different.  The example you cite is neither proprietary nor identical.

Further trolling will not be permitted on our GitHub
https://twitter.com/DEXAG_TokenWire/status/1197611116425166848?s=20
